"""empty message

Revision ID: 02d3b5698405
Revises: 3ca538c7be31
Create Date: 2021-10-13 13:30:03.995294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d3b5698405'
down_revision = '3ca538c7be31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('file', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'file')
    # ### end Alembic commands ###
