"""empty message

Revision ID: 3ca538c7be31
Revises: e6e837e08e3c
Create Date: 2021-10-09 13:42:36.337078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca538c7be31'
down_revision = 'e6e837e08e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('update_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'update_date')
    op.drop_column('answer', 'update_date')
    # ### end Alembic commands ###
