"""empty message

Revision ID: 404983e62ce1
Revises: 0d3310c477cf
Create Date: 2021-10-06 22:19:35.110080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404983e62ce1'
down_revision = '0d3310c477cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('user_id', sa.String(length=255), nullable=False))
    op.add_column('answer', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('article', sa.Column('user_id', sa.String(length=255), nullable=False))
    op.add_column('article', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'name')
    op.drop_column('article', 'user_id')
    op.drop_column('answer', 'name')
    op.drop_column('answer', 'user_id')
    # ### end Alembic commands ###
